# Numpy introduction: basics

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

# import

In [93]:
# Import numpy
import numpy as np

# Create an array

In [94]:
# Create a 1D array
a = np.array([1, 2, 3])
print(a)

# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(f'---- \n{b}')

# Create a 3D array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f'---- \n{c}')

[1 2 3]
---- 
[[1 2 3]
 [4 5 6]]
---- 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [95]:
# Create an array of zeros, ones, random numbers, and evenly spaced values

In [96]:
# Create an array of zeros
d = np.zeros((2, 3))
print(d)

# Create an array of ones
e = np.ones((5, 2))
print(e)



[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# Create an array of random numbers
The difference between random.random and random.rand is teh way the input is passed. random.random takes a tuple as input, while random.rand takes the dimensions as separate arguments.

In [97]:
# Create an array of random numbers (between 0 and 1) with uniform distribution
f = np.random.random((2, 3)) # random numbers between 0 and 1 # 2x3 array # random.random is a method of the random module in Python, and it generates a random float between 0 and 1.
print(f'----\n np.random.random: \n{f}')
# Other ways to create random numbers
f_1 = np.random.rand(2, 3) # random numbers between 0 and 1 # 2x3 array 
print(f'----\n np.random.rand: \n{f_1}')

----
 np.random.random: 
[[0.05399929 0.55969632 0.49621175]
 [0.14134987 0.41856816 0.28880474]]
----
 np.random.rand: 
[[0.74000501 0.28925614 0.30322824]
 [0.26054703 0.33317693 0.52497365]]


Create an array of random numbers with normal distribution

In [98]:
f_2 = np.random.randn(2, 3) # random numbers from a normal distribution # 2x3 array
print(f'----\n np.random.randn: \n{f_2}')

----
 np.random.randn: 
[[ 2.7276327  -0.07309772 -0.87190894]
 [ 0.48728896 -0.41327082 -0.61905954]]


Create an array of random integers

In [99]:
f_3 = np.random.randint(1, 100, (2, 3)) # random integers between 1 and 100 # 2x3 array
print(f'----\n np.random.randint: \n{f_3}')

----
 np.random.randint: 
[[22 90 15]
 [23 63 30]]


Create an array of random choice

In [100]:
f_4 = np.random.choice([1, 5.5, 2*np.pi, 1e2], (2, 3)) # random choice from a list # 2x3 array
print(f'----\n np.random.choice: \n{f_4}')

----
 np.random.choice: 
[[  6.28318531   1.           6.28318531]
 [100.           5.5          6.28318531]]


# arange, linspace, eye

In [101]:
# Create an array of evenly spaced values (arange)
g = np.arange(10) # 10 is not included but 0 is included
h = np.arange(12, 30, 3) # start, stop, step # stop is not included
print(g)
print(h)
print(type(g))
print(type(g[0]))

[0 1 2 3 4 5 6 7 8 9]
[12 15 18 21 24 27]
<class 'numpy.ndarray'>
<class 'numpy.int32'>


In [102]:
# Create an array of evenly spaced values
i = np.linspace(0, 2, 9) # start, stop, number of points
print(i)
print(type(i))
print(type(i[0]))

# Create an array of evenly spaced values
j = np.linspace(0, 2*np.pi, 10) # start, stop, number of points
print(j)
print()
# The difference between linspace and arange is that linspace returns the number of points you want, while arange returns the step size you want.
# linspace is more useful when you know how many points you want, and arange is more useful when you know what step size you want.
# also, linspace is inclusive of the stop value, while arange is not.
# linspace outputs a float array, while arange outputs an int array.

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]


In [103]:
# Create an array of evenly spaced values
k = np.eye(3) # 3x3 identity matrix
print(k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Reshape

In [104]:
# Reshape an array # The new shape should be compatible with the original shape it means the number of elements should be the same in both shapes
l = np.arange(6).reshape(2, 3)
print(l)


[[0 1 2]
 [3 4 5]]


In [105]:
# Reshape an array
m = np.arange(24).reshape(2, 3, 4)
print(m)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# Basic operations

In [106]:
# Basic operations
n = np.array([20, 30, 40, 50])
o = np.arange(4)
print(n)
print(o)
print(n - o)
print(o**2)
print(10 * np.sin(n))
print(n < 35)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


# Matrix multiplication

In [107]:
# Matrix multiplication
p = np.array([[1, 1], [0, 1]])
q = np.array([[2, 0], [3, 4]])
print(p)
print(q)
print(f'-------\n elementwise product p*q: \n{p * q}') # elementwise product
print(f'-------\n matrix product p@q: \n{p @ q}') # matrix product
print(f'-------\n another matrix product p.dot(q): \n{p.dot(q)}') # another matrix product

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
-------
 elementwise product p*q: 
[[2 0]
 [0 4]]
-------
 matrix product p@q: 
[[5 4]
 [3 4]]
-------
 another matrix product p.dot(q): 
[[5 4]
 [3 4]]
